# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlPanel.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GameControlPanel(object):
    def setupUi(self, GameControlPanel):
        GameControlPanel.setObjectName("GameControlPanel")
        GameControlPanel.resize(670, 341)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GameControlPanel.sizePolicy().hasHeightForWidth())
        GameControlPanel.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(GameControlPanel)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 611, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.BedBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BedBox.sizePolicy().hasHeightForWidth())
        self.BedBox.setSizePolicy(sizePolicy)
        self.BedBox.setSuffix("")
        self.BedBox.setMinimum(50)
        self.BedBox.setMaximum(500)
        self.BedBox.setSingleStep(100)
        self.BedBox.setProperty("value", 100)
        self.BedBox.setDisplayIntegerBase(10)
        self.BedBox.setObjectName("BedBox")
        self.gridLayout_2.addWidget(self.BedBox, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.TransUpdate = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TransUpdate.setFont(font)
        self.TransUpdate.setObjectName("TransUpdate")
        self.gridLayout_2.addWidget(self.TransUpdate, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.DistUpdate = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DistUpdate.setFont(font)
        self.DistUpdate.setObjectName("DistUpdate")
        self.gridLayout_2.addWidget(self.DistUpdate, 1, 0, 1, 1)
        self.BedUpdate = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BedUpdate.setFont(font)
        self.BedUpdate.setObjectName("BedUpdate")
        self.gridLayout_2.addWidget(self.BedUpdate, 0, 0, 1, 1)
        self.DistBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DistBox.sizePolicy().hasHeightForWidth())
        self.DistBox.setSizePolicy(sizePolicy)
        self.DistBox.setSuffix("")
        self.DistBox.setMinimum(-100)
        self.DistBox.setMaximum(500)
        self.DistBox.setSingleStep(10)
        self.DistBox.setProperty("value", 100)
        self.DistBox.setDisplayIntegerBase(10)
        self.DistBox.setObjectName("DistBox")
        self.gridLayout_2.addWidget(self.DistBox, 1, 2, 1, 1)
        self.TranBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TranBox.sizePolicy().hasHeightForWidth())
        self.TranBox.setSizePolicy(sizePolicy)
        self.TranBox.setSuffix("")
        self.TranBox.setMinimum(0)
        self.TranBox.setMaximum(100)
        self.TranBox.setSingleStep(5)
        self.TranBox.setProperty("value", 80)
        self.TranBox.setDisplayIntegerBase(10)
        self.TranBox.setObjectName("TranBox")
        self.gridLayout_2.addWidget(self.TranBox, 2, 2, 1, 1)
        self.ExitGame = QtWidgets.QPushButton(self.centralwidget)
        self.ExitGame.setGeometry(QtCore.QRect(200, 260, 242, 33))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ExitGame.setFont(font)
        self.ExitGame.setObjectName("ExitGame")
        GameControlPanel.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GameControlPanel)
        self.statusbar.setObjectName("statusbar")
        GameControlPanel.setStatusBar(self.statusbar)

        self.retranslateUi(GameControlPanel)
        QtCore.QMetaObject.connectSlotsByName(GameControlPanel)

    def retranslateUi(self, GameControlPanel):
        _translate = QtCore.QCoreApplication.translate
        GameControlPanel.setWindowTitle(_translate("GameControlPanel", "Game Control Panel"))
        self.label.setText(_translate("GameControlPanel", "Add Isolation Beds"))
        self.label_2.setText(_translate("GameControlPanel", " Update Travel Distance"))
        self.TransUpdate.setText(_translate("GameControlPanel", "Update"))
        self.label_3.setText(_translate("GameControlPanel", "Update Trans Prob (%)"))
        self.DistUpdate.setText(_translate("GameControlPanel", "Update"))
        self.BedUpdate.setText(_translate("GameControlPanel", "Update"))
        self.ExitGame.setText(_translate("GameControlPanel", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameControlPanel = QtWidgets.QMainWindow()
    ui = Ui_GameControlPanel()
    ui.setupUi(GameControlPanel)
    GameControlPanel.show()
    sys.exit(app.exec_())

