# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameControlPanel.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 419)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 741, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.BedValueBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BedValueBox.sizePolicy().hasHeightForWidth())
        self.BedValueBox.setSizePolicy(sizePolicy)
        self.BedValueBox.setSuffix("")
        self.BedValueBox.setMinimum(1)
        self.BedValueBox.setMaximum(2500)
        self.BedValueBox.setProperty("value", 200)
        self.BedValueBox.setDisplayIntegerBase(10)
        self.BedValueBox.setObjectName("BedValueBox")
        self.gridLayout_2.addWidget(self.BedValueBox, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.InfectionRateUpdateButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InfectionRateUpdateButton.setFont(font)
        self.InfectionRateUpdateButton.setObjectName("InfectionRateUpdateButton")
        self.gridLayout_2.addWidget(self.InfectionRateUpdateButton, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.InfectionRateBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfectionRateBox.sizePolicy().hasHeightForWidth())
        self.InfectionRateBox.setSizePolicy(sizePolicy)
        self.InfectionRateBox.setMaximum(1.0)
        self.InfectionRateBox.setSingleStep(0.01)
        self.InfectionRateBox.setProperty("value", 0.75)
        self.InfectionRateBox.setObjectName("InfectionRateBox")
        self.gridLayout_2.addWidget(self.InfectionRateBox, 2, 2, 1, 1)
        self.FlowIntentionUpdateButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FlowIntentionUpdateButton.setFont(font)
        self.FlowIntentionUpdateButton.setObjectName("FlowIntentionUpdateButton")
        self.gridLayout_2.addWidget(self.FlowIntentionUpdateButton, 1, 0, 1, 1)
        self.BedUpdateButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BedUpdateButton.setFont(font)
        self.BedUpdateButton.setObjectName("BedUpdateButton")
        self.gridLayout_2.addWidget(self.BedUpdateButton, 0, 0, 1, 1)
        self.FlowIntentionBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlowIntentionBox.sizePolicy().hasHeightForWidth())
        self.FlowIntentionBox.setSizePolicy(sizePolicy)
        self.FlowIntentionBox.setDecimals(1)
        self.FlowIntentionBox.setMinimum(1.0)
        self.FlowIntentionBox.setMaximum(5.0)
        self.FlowIntentionBox.setSingleStep(0.5)
        self.FlowIntentionBox.setProperty("value", 5.0)
        self.FlowIntentionBox.setObjectName("FlowIntentionBox")
        self.gridLayout_2.addWidget(self.FlowIntentionBox, 1, 2, 1, 1)
        self.ExitGame = QtWidgets.QPushButton(self.centralwidget)
        self.ExitGame.setGeometry(QtCore.QRect(230, 330, 311, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ExitGame.setFont(font)
        self.ExitGame.setObjectName("ExitGame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Isolation Beds"))
        self.label_2.setText(_translate("MainWindow", "Flow Intention"))
        self.InfectionRateUpdateButton.setText(_translate("MainWindow", "Update"))
        self.label_3.setText(_translate("MainWindow", "Infection Rate"))
        self.FlowIntentionUpdateButton.setText(_translate("MainWindow", "Update"))
        self.BedUpdateButton.setText(_translate("MainWindow", "Update"))
        self.ExitGame.setText(_translate("MainWindow", "Exit Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

