# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_COVID19Simulation(object):
    def setupUi(self, COVID19Simulation):
        COVID19Simulation.setObjectName("COVID19Simulation")
        COVID19Simulation.resize(1618, 1060)
        self.centralwidget = QtWidgets.QWidget(COVID19Simulation)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1050, 70, 391, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1450, 70, 91, 521))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_18time = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18time.setFont(font)
        self.label_18time.setObjectName("label_18time")
        self.verticalLayout_2.addWidget(self.label_18time)
        self.label_10Totalpopulation = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10Totalpopulation.setFont(font)
        self.label_10Totalpopulation.setObjectName("label_10Totalpopulation")
        self.verticalLayout_2.addWidget(self.label_10Totalpopulation)
        self.label_11healthy = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11healthy.setFont(font)
        self.label_11healthy.setObjectName("label_11healthy")
        self.verticalLayout_2.addWidget(self.label_11healthy)
        self.label_11healthy_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11healthy_2.setFont(font)
        self.label_11healthy_2.setObjectName("label_11healthy_2")
        self.verticalLayout_2.addWidget(self.label_11healthy_2)
        self.label_13symtomatic = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13symtomatic.setFont(font)
        self.label_13symtomatic.setObjectName("label_13symtomatic")
        self.verticalLayout_2.addWidget(self.label_13symtomatic)
        self.label_12incubation = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12incubation.setFont(font)
        self.label_12incubation.setObjectName("label_12incubation")
        self.verticalLayout_2.addWidget(self.label_12incubation)
        self.label_15isolated = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15isolated.setFont(font)
        self.label_15isolated.setObjectName("label_15isolated")
        self.verticalLayout_2.addWidget(self.label_15isolated)
        self.label_16remaning = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16remaning.setFont(font)
        self.label_16remaning.setObjectName("label_16remaning")
        self.verticalLayout_2.addWidget(self.label_16remaning)
        self.label_14nonsymtomatic = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14nonsymtomatic.setFont(font)
        self.label_14nonsymtomatic.setObjectName("label_14nonsymtomatic")
        self.verticalLayout_2.addWidget(self.label_14nonsymtomatic)
        self.label_17dead = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17dead.setFont(font)
        self.label_17dead.setObjectName("label_17dead")
        self.verticalLayout_2.addWidget(self.label_17dead)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1050, 620, 371, 281))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(1450, 620, 91, 281))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        COVID19Simulation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(COVID19Simulation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1618, 21))
        self.menubar.setObjectName("menubar")
        COVID19Simulation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(COVID19Simulation)
        self.statusbar.setObjectName("statusbar")
        COVID19Simulation.setStatusBar(self.statusbar)

        self.retranslateUi(COVID19Simulation)
        QtCore.QMetaObject.connectSlotsByName(COVID19Simulation)

    def retranslateUi(self, COVID19Simulation):
        _translate = QtCore.QCoreApplication.translate
        COVID19Simulation.setWindowTitle(_translate("COVID19Simulation", "MainWindow"))
        self.label_7.setText(_translate("COVID19Simulation", "Current time (day):"))
        self.label.setText(_translate("COVID19Simulation", "Total population on board:"))
        self.label_2.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#00ff00;\">Healthy people (including recovered):</span></p></body></html>"))
        self.label_4.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" font-size:11pt; font-style:italic; color:#00aa00;\">Recovered:</span></p></body></html>"))
        self.label_3.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#ff00ff;\">People in incubation period:</span></p></body></html>"))
        self.label_9.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#ff0000;\">Symptomatic patients:</span></p></body></html>"))
        self.label_6.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#00aaff;\">Isolated patients:</span></p></body></html>"))
        self.label_22.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" font-size:11pt; font-style:italic; color:#00aaff;\">*Remaining beds in isolation room:</span></p></body></html>"))
        self.label_5.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" font-size:11pt; font-style:italic; color:#00aaff;\">*Demand for extra beds:</span></p></body></html>"))
        self.label_8.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#000000;\">Dead people:</span></p></body></html>"))
        self.label_18time.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">T</span></p></body></html>"))
        self.label_10Totalpopulation.setText(_translate("COVID19Simulation", "A"))
        self.label_11healthy.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#00ff00;\">B</span></p></body></html>"))
        self.label_11healthy_2.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#00aa00;\">B2</span></p></body></html>"))
        self.label_13symtomatic.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#ff00ff;\">C</span></p></body></html>"))
        self.label_12incubation.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#ff0000;\">D</span></p></body></html>"))
        self.label_15isolated.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#00aaff;\">E</span></p></body></html>"))
        self.label_16remaning.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#00aaff;\">F</span></p></body></html>"))
        self.label_14nonsymtomatic.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#00aaff;\">G</span></p></body></html>"))
        self.label_17dead.setText(_translate("COVID19Simulation", "<html><head/><body><p><span style=\" color:#000000;\">H</span></p></body></html>"))
        self.label_10.setText(_translate("COVID19Simulation", "Total isolation beds:"))
        self.label_12.setText(_translate("COVID19Simulation", "Transmission probability:"))
        self.label_11.setText(_translate("COVID19Simulation", "Mean travel distance:"))
        self.label_13.setText(_translate("COVID19Simulation", "Incubation period:"))
        self.label_14.setText(_translate("COVID19Simulation", "Isolation latency:"))
        self.label_15.setText(_translate("COVID19Simulation", "Safety distance:"))
        self.label_17.setText(_translate("COVID19Simulation", "I"))
        self.label_16.setText(_translate("COVID19Simulation", "J"))
        self.label_18.setText(_translate("COVID19Simulation", "K"))
        self.label_19.setText(_translate("COVID19Simulation", "L"))
        self.label_20.setText(_translate("COVID19Simulation", "M"))
        self.label_21.setText(_translate("COVID19Simulation", "N"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    COVID19Simulation = QtWidgets.QMainWindow()
    ui = Ui_COVID19Simulation()
    ui.setupUi(COVID19Simulation)
    COVID19Simulation.show()
    sys.exit(app.exec_())

